-- =====================================================================
-- Phase 3 — Streams + Tasks + MERGE: incremental ELT with SCD Type 2
-- =====================================================================
USE ROLE ACCOUNTADMIN;
USE DATABASE RETAIL_DW;
USE WAREHOUSE TRANSFORM_WH;

-- ---- 1. Target tables ----
CREATE OR REPLACE TABLE STAGING.DIM_CUSTOMER (
  CUSTOMER_SK   NUMBER IDENTITY START 1 INCREMENT 1,
  CUSTOMER_ID   STRING       NOT NULL,       -- business key
  FULL_NAME     STRING,
  EMAIL         STRING,                      -- PII
  PHONE         STRING,                      -- PII
  CITY          STRING,
  STATE         STRING,
  SIGNUP_DATE   DATE,
  VALID_FROM    TIMESTAMP_NTZ NOT NULL,
  VALID_TO      TIMESTAMP_NTZ,               -- NULL = open version
  IS_CURRENT    BOOLEAN       NOT NULL DEFAULT TRUE
);

CREATE OR REPLACE TABLE ANALYTICS.FACT_ORDERS (
  ORDER_ID      STRING NOT NULL,
  CUSTOMER_SK   NUMBER,
  ORDER_TS      TIMESTAMP_NTZ,
  ORDER_DATE    DATE,
  STATUS        STRING,
  CHANNEL       STRING,
  ITEMS         NUMBER,
  ORDER_TOTAL   NUMBER(12,2),
  _UPDATED_AT   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ---- 2. Bootstrap the baseline before turning on Streams ----
-- Run this once after Phase 2's batch0 COPY.  Streams are deliberately created
-- *after* this bootstrap so that the task chain sees only future S3 increments.
INSERT INTO STAGING.DIM_CUSTOMER
  (CUSTOMER_ID, FULL_NAME, EMAIL, PHONE, CITY, STATE, SIGNUP_DATE,
   VALID_FROM, VALID_TO, IS_CURRENT)
SELECT CUSTOMER_ID, FULL_NAME, EMAIL, PHONE, CITY, STATE,
       TRY_TO_DATE(SIGNUP_DATE),
       COALESCE(TRY_TO_TIMESTAMP(UPDATED_AT), CURRENT_TIMESTAMP()), NULL, TRUE
FROM RAW.CUSTOMERS_RAW
QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID
                           ORDER BY TRY_TO_TIMESTAMP(UPDATED_AT) DESC) = 1;

INSERT INTO ANALYTICS.FACT_ORDERS
  (ORDER_ID, CUSTOMER_SK, ORDER_TS, ORDER_DATE, STATUS, CHANNEL, ITEMS, ORDER_TOTAL)
SELECT o.ORDER_ID, d.CUSTOMER_SK, TRY_TO_TIMESTAMP(o.ORDER_TS),
       DATE(TRY_TO_TIMESTAMP(o.ORDER_TS)), o.STATUS, o.CHANNEL,
       TRY_TO_NUMBER(o.ITEMS), TRY_TO_NUMBER(o.ORDER_TOTAL, 12, 2)
FROM RAW.ORDERS_RAW o
LEFT JOIN STAGING.DIM_CUSTOMER d
  ON d.CUSTOMER_ID = o.CUSTOMER_ID AND d.IS_CURRENT
QUALIFY ROW_NUMBER() OVER (PARTITION BY o.ORDER_ID
                           ORDER BY TRY_TO_TIMESTAMP(o.ORDER_TS) DESC) = 1;

-- Capture only rows landing after the baseline is in the dimensional model.
CREATE OR REPLACE STREAM RAW.CUSTOMERS_STREAM ON TABLE RAW.CUSTOMERS_RAW;
CREATE OR REPLACE STREAM RAW.ORDERS_STREAM    ON TABLE RAW.ORDERS_RAW;

-- ---- 3. SCD Type 2 procedure for DIM_CUSTOMER ----
-- Two steps in one transaction:
--   (a) close current rows whose attributes changed (set VALID_TO / IS_CURRENT=FALSE)
--   (b) insert a fresh open version for every new or changed customer
CREATE OR REPLACE PROCEDURE STAGING.SP_MERGE_DIM_CUSTOMER()
RETURNS STRING LANGUAGE SQL AS
$$
BEGIN
  BEGIN TRANSACTION;

  CREATE OR REPLACE TEMPORARY TABLE STAGING._CUST_DELTA AS
  SELECT CUSTOMER_ID, FULL_NAME, EMAIL, PHONE, CITY, STATE,
         TRY_TO_DATE(SIGNUP_DATE) AS SIGNUP_DATE,
         TRY_TO_TIMESTAMP(UPDATED_AT) AS UPDATED_AT
  FROM RAW.CUSTOMERS_STREAM
  WHERE METADATA$ACTION = 'INSERT'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID
                             ORDER BY TRY_TO_TIMESTAMP(UPDATED_AT) DESC) = 1;

  -- (a) close changed current versions
  MERGE INTO STAGING.DIM_CUSTOMER d
  USING STAGING._CUST_DELTA s
    ON d.CUSTOMER_ID = s.CUSTOMER_ID AND d.IS_CURRENT
  WHEN MATCHED AND (   NOT EQUAL_NULL(d.CITY,  s.CITY)
                    OR NOT EQUAL_NULL(d.EMAIL, s.EMAIL)
                    OR NOT EQUAL_NULL(d.PHONE, s.PHONE)
                    OR NOT EQUAL_NULL(d.FULL_NAME, s.FULL_NAME))
  THEN UPDATE SET d.VALID_TO = s.UPDATED_AT, d.IS_CURRENT = FALSE;

  -- (b) open a new version for new customers and just-closed ones
  INSERT INTO STAGING.DIM_CUSTOMER
    (CUSTOMER_ID, FULL_NAME, EMAIL, PHONE, CITY, STATE, SIGNUP_DATE,
     VALID_FROM, VALID_TO, IS_CURRENT)
  SELECT s.CUSTOMER_ID, s.FULL_NAME, s.EMAIL, s.PHONE, s.CITY, s.STATE,
         s.SIGNUP_DATE, COALESCE(s.UPDATED_AT, CURRENT_TIMESTAMP()), NULL, TRUE
  FROM STAGING._CUST_DELTA s
  LEFT JOIN STAGING.DIM_CUSTOMER d
    ON d.CUSTOMER_ID = s.CUSTOMER_ID AND d.IS_CURRENT
  WHERE d.CUSTOMER_ID IS NULL;

  COMMIT;
  RETURN 'DIM_CUSTOMER merged';
END;
$$;

-- ---- 4. Incremental fact MERGE (idempotent upsert on ORDER_ID) ----
CREATE OR REPLACE PROCEDURE ANALYTICS.SP_MERGE_FACT_ORDERS()
RETURNS STRING LANGUAGE SQL AS
$$
BEGIN
  MERGE INTO ANALYTICS.FACT_ORDERS f
  USING (
    SELECT o.ORDER_ID,
           d.CUSTOMER_SK,
           TRY_TO_TIMESTAMP(o.ORDER_TS)        AS ORDER_TS,
           DATE(TRY_TO_TIMESTAMP(o.ORDER_TS))  AS ORDER_DATE,
           o.STATUS, o.CHANNEL,
           TRY_TO_NUMBER(o.ITEMS)              AS ITEMS,
           TRY_TO_NUMBER(o.ORDER_TOTAL, 12, 2) AS ORDER_TOTAL
    FROM RAW.ORDERS_STREAM o
    LEFT JOIN STAGING.DIM_CUSTOMER d
      ON d.CUSTOMER_ID = o.CUSTOMER_ID AND d.IS_CURRENT
    WHERE o.METADATA$ACTION = 'INSERT'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY o.ORDER_ID
                               ORDER BY TRY_TO_TIMESTAMP(o.ORDER_TS) DESC) = 1
  ) s
  ON f.ORDER_ID = s.ORDER_ID
  WHEN MATCHED THEN UPDATE SET
       f.STATUS = s.STATUS, f.ORDER_TOTAL = s.ORDER_TOTAL,
       f._UPDATED_AT = CURRENT_TIMESTAMP()
  WHEN NOT MATCHED THEN INSERT
       (ORDER_ID, CUSTOMER_SK, ORDER_TS, ORDER_DATE, STATUS, CHANNEL, ITEMS, ORDER_TOTAL)
       VALUES (s.ORDER_ID, s.CUSTOMER_SK, s.ORDER_TS, s.ORDER_DATE,
               s.STATUS, s.CHANNEL, s.ITEMS, s.ORDER_TOTAL);
  RETURN 'FACT_ORDERS merged';
END;
$$;

-- ---- 5. Task tree: dims first, facts after; skip when nothing to do ----
-- Snowflake task predecessors must be in the same schema, so both tasks live
-- in ANALYTICS even though the dimension procedure lives in STAGING.
CREATE OR REPLACE TASK ANALYTICS.TASK_LOAD_DIMS
  WAREHOUSE = TRANSFORM_WH
  SCHEDULE = 'USING CRON */5 * * * * UTC'
  WHEN SYSTEM$STREAM_HAS_DATA('RETAIL_DW.RAW.CUSTOMERS_STREAM')
    OR SYSTEM$STREAM_HAS_DATA('RETAIL_DW.RAW.ORDERS_STREAM')
AS CALL STAGING.SP_MERGE_DIM_CUSTOMER();

CREATE OR REPLACE TASK ANALYTICS.TASK_LOAD_FACTS
  WAREHOUSE = TRANSFORM_WH
  AFTER ANALYTICS.TASK_LOAD_DIMS
AS CALL ANALYTICS.SP_MERGE_FACT_ORDERS();

ALTER TASK ANALYTICS.TASK_LOAD_FACTS RESUME;   -- children first
ALTER TASK ANALYTICS.TASK_LOAD_DIMS  RESUME;

-- For a deterministic demo after placing a new S3 increment, optionally run:
-- EXECUTE TASK ANALYTICS.TASK_LOAD_DIMS;

-- ---- VERIFY (PLAN.md acceptance) ----
SELECT COUNT(*) FROM STAGING.DIM_CUSTOMER WHERE IS_CURRENT;      -- ~50,000
SELECT COUNT(*) FROM ANALYTICS.FACT_ORDERS;                       -- ~500,000

-- Now drop increments/customers_batch1.csv + orders_batch1.csv into S3, wait
-- for Snowpipe (~1 min) + next task tick (<=5 min), then prove SCD2:
SELECT CUSTOMER_ID, CITY, VALID_FROM, VALID_TO, IS_CURRENT
FROM STAGING.DIM_CUSTOMER
WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM STAGING.DIM_CUSTOMER
                      GROUP BY 1 HAVING COUNT(*) > 1)
ORDER BY CUSTOMER_ID, VALID_FROM
LIMIT 20;    -- expect old city rows closed (IS_CURRENT=FALSE) + new open rows

SELECT NAME, STATE, SCHEDULED_TIME
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
ORDER BY SCHEDULED_TIME DESC LIMIT 10;   -- SUCCEEDED + SKIPPED (no-data) runs
