-- =====================================================================
-- Phase 4 — Governance: 3-tier RBAC, dynamic masking, Time Travel, clones
-- =====================================================================
USE ROLE ACCOUNTADMIN;
USE DATABASE RETAIL_DW;

-- ---- 1. Role hierarchy: VIEWER < ANALYST < ENGINEER < SYSADMIN ----
CREATE ROLE IF NOT EXISTS DE_ENGINEER;
CREATE ROLE IF NOT EXISTS DE_ANALYST;
CREATE ROLE IF NOT EXISTS DE_VIEWER;
GRANT ROLE DE_VIEWER  TO ROLE DE_ANALYST;    -- analyst inherits viewer
GRANT ROLE DE_ANALYST TO ROLE DE_ENGINEER;   -- engineer inherits analyst
GRANT ROLE DE_ENGINEER TO ROLE SYSADMIN;

-- ---- 2. Grants per tier ----
-- VIEWER: read curated ANALYTICS only, on the BI warehouse
GRANT USAGE ON DATABASE RETAIL_DW TO ROLE DE_VIEWER;
GRANT USAGE ON SCHEMA ANALYTICS   TO ROLE DE_VIEWER;
GRANT SELECT ON ALL TABLES    IN SCHEMA ANALYTICS TO ROLE DE_VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS TO ROLE DE_VIEWER;
GRANT USAGE ON WAREHOUSE BI_WH TO ROLE DE_VIEWER;

-- ANALYST: + read STAGING (dims incl. history)
GRANT USAGE ON SCHEMA STAGING TO ROLE DE_ANALYST;
GRANT SELECT ON ALL TABLES    IN SCHEMA STAGING TO ROLE DE_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA STAGING TO ROLE DE_ANALYST;

-- ENGINEER: + full pipeline control incl. RAW and transform compute
GRANT USAGE ON SCHEMA RAW TO ROLE DE_ENGINEER;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA RAW TO ROLE DE_ENGINEER;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE DE_ENGINEER;
GRANT USAGE ON WAREHOUSE LOAD_WH      TO ROLE DE_ENGINEER;

-- Give yourself all three (so you can demo switching):
GRANT ROLE DE_ENGINEER TO USER "<YOUR_USERNAME>";
GRANT ROLE DE_ANALYST  TO USER "<YOUR_USERNAME>";
GRANT ROLE DE_VIEWER   TO USER "<YOUR_USERNAME>";

-- ---- 3. Dynamic data masking on PII ----
CREATE OR REPLACE MASKING POLICY STAGING.MASK_EMAIL AS (VAL STRING)
  RETURNS STRING ->
  CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'DE_ENGINEER') THEN VAL
       ELSE CONCAT(LEFT(VAL, 2), '****@masked.com') END;

CREATE OR REPLACE MASKING POLICY STAGING.MASK_PHONE AS (VAL STRING)
  RETURNS STRING ->
  CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'DE_ENGINEER') THEN VAL
       ELSE '***-***-****' END;

ALTER TABLE STAGING.DIM_CUSTOMER MODIFY COLUMN EMAIL SET MASKING POLICY STAGING.MASK_EMAIL;
ALTER TABLE STAGING.DIM_CUSTOMER MODIFY COLUMN PHONE SET MASKING POLICY STAGING.MASK_PHONE;

-- VERIFY masking live (run both, screenshot both):
USE ROLE DE_ANALYST;
SELECT CUSTOMER_ID, EMAIL, PHONE FROM STAGING.DIM_CUSTOMER LIMIT 5;  -- masked
USE ROLE DE_ENGINEER;
SELECT CUSTOMER_ID, EMAIL, PHONE FROM STAGING.DIM_CUSTOMER LIMIT 5;  -- clear
USE ROLE ACCOUNTADMIN;

-- ---- 4. Time Travel (safe, isolated demonstration table) ----
-- Keep resilience demos away from the live dimension and fact tables.
CREATE OR REPLACE TABLE ANALYTICS.TIME_TRAVEL_DEMO AS
SELECT 'C000001' AS CUSTOMER_ID, 'before_change' AS DEMO_VALUE;
UPDATE ANALYTICS.TIME_TRAVEL_DEMO SET DEMO_VALUE = 'after_change';
SELECT * FROM ANALYTICS.TIME_TRAVEL_DEMO AT(OFFSET => -60);  -- before_change

DROP TABLE ANALYTICS.TIME_TRAVEL_DEMO;
UNDROP TABLE ANALYTICS.TIME_TRAVEL_DEMO;    -- back instantly; screenshot this
DROP TABLE ANALYTICS.TIME_TRAVEL_DEMO;      -- optional cleanup

-- ---- 5. Zero-copy clone: instant, storage-free dev environment ----
DROP DATABASE IF EXISTS RETAIL_DW_DEV;      -- disposable project sandbox only
CREATE DATABASE RETAIL_DW_DEV CLONE RETAIL_DW;
-- prove isolation: change dev, prod untouched
UPDATE RETAIL_DW_DEV.STAGING.DIM_CUSTOMER SET CITY='DEVTEST' WHERE CUSTOMER_ID='C000002';
SELECT 'prod' src, CITY FROM RETAIL_DW.STAGING.DIM_CUSTOMER     WHERE CUSTOMER_ID='C000002'
UNION ALL
SELECT 'dev', CITY FROM RETAIL_DW_DEV.STAGING.DIM_CUSTOMER WHERE CUSTOMER_ID='C000002';
