-- =====================================================================
-- Phase 4 — Governance: 3-tier RBAC, dynamic masking, Time Travel, clones
-- =====================================================================
USE ROLE ACCOUNTADMIN;
USE DATABASE RETAIL_DW;

-- ---- 1. Role hierarchy: VIEWER < ANALYST < ENGINEER < SYSADMIN ----
CREATE ROLE IF NOT EXISTS DE_ENGINEER;
CREATE ROLE IF NOT EXISTS DE_ANALYST;
CREATE ROLE IF NOT EXISTS DE_VIEWER;
GRANT ROLE DE_VIEWER  TO ROLE DE_ANALYST;    -- analyst inherits viewer
GRANT ROLE DE_ANALYST TO ROLE DE_ENGINEER;   -- engineer inherits analyst
GRANT ROLE DE_ENGINEER TO ROLE SYSADMIN;

-- ---- 2. Grants per tier ----
-- VIEWER: read curated ANALYTICS only, on the BI warehouse
GRANT USAGE ON DATABASE RETAIL_DW TO ROLE DE_VIEWER;
GRANT USAGE ON SCHEMA ANALYTICS   TO ROLE DE_VIEWER;
GRANT SELECT ON ALL TABLES    IN SCHEMA ANALYTICS TO ROLE DE_VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS TO ROLE DE_VIEWER;
GRANT USAGE ON WAREHOUSE BI_WH TO ROLE DE_VIEWER;

-- ANALYST: + read STAGING (dims incl. history)
GRANT USAGE ON SCHEMA STAGING TO ROLE DE_ANALYST;
GRANT SELECT ON ALL TABLES    IN SCHEMA STAGING TO ROLE DE_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA STAGING TO ROLE DE_ANALYST;

-- ENGINEER: + full pipeline control incl. RAW and transform compute
GRANT USAGE ON SCHEMA RAW TO ROLE DE_ENGINEER;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA RAW TO ROLE DE_ENGINEER;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE DE_ENGINEER;
GRANT USAGE ON WAREHOUSE LOAD_WH      TO ROLE DE_ENGINEER;

-- Give yourself all three (so you can demo switching):
GRANT ROLE DE_ENGINEER TO USER "<YOUR_USERNAME>";
GRANT ROLE DE_ANALYST  TO USER "<YOUR_USERNAME>";
GRANT ROLE DE_VIEWER   TO USER "<YOUR_USERNAME>";

-- ---- 3. Dynamic data masking on PII ----
CREATE OR REPLACE MASKING POLICY STAGING.MASK_EMAIL AS (VAL STRING)
  RETURNS STRING ->
  CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'DE_ENGINEER') THEN VAL
       ELSE CONCAT(LEFT(VAL, 2), '****@masked.com') END;

CREATE OR REPLACE MASKING POLICY STAGING.MASK_PHONE AS (VAL STRING)
  RETURNS STRING ->
  CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'DE_ENGINEER') THEN VAL
       ELSE '***-***-****' END;

ALTER TABLE STAGING.DIM_CUSTOMER MODIFY COLUMN EMAIL SET MASKING POLICY STAGING.MASK_EMAIL;
ALTER TABLE STAGING.DIM_CUSTOMER MODIFY COLUMN PHONE SET MASKING POLICY STAGING.MASK_PHONE;

-- VERIFY masking live (run both, screenshot both):
USE ROLE DE_ANALYST;
SELECT CUSTOMER_ID, EMAIL, PHONE FROM STAGING.DIM_CUSTOMER LIMIT 5;  -- masked
USE ROLE DE_ENGINEER;
SELECT CUSTOMER_ID, EMAIL, PHONE FROM STAGING.DIM_CUSTOMER LIMIT 5;  -- clear
USE ROLE ACCOUNTADMIN;

-- ---- 4. Time Travel ----
UPDATE STAGING.DIM_CUSTOMER SET CITY = 'OOPS' WHERE CUSTOMER_ID = 'C000001';
SELECT CITY FROM STAGING.DIM_CUSTOMER AT(OFFSET => -60)   -- 1 minute ago
WHERE CUSTOMER_ID = 'C000001';                             -- original value
-- restore:
UPDATE STAGING.DIM_CUSTOMER d
SET CITY = h.CITY
FROM (SELECT CUSTOMER_ID, CITY FROM STAGING.DIM_CUSTOMER AT(OFFSET => -60)
      WHERE CUSTOMER_ID = 'C000001') h
WHERE d.CUSTOMER_ID = h.CUSTOMER_ID;

DROP TABLE ANALYTICS.FACT_ORDERS;
UNDROP TABLE ANALYTICS.FACT_ORDERS;    -- back instantly; screenshot this

-- ---- 5. Zero-copy clone: instant, storage-free dev environment ----
CREATE DATABASE RETAIL_DW_DEV CLONE RETAIL_DW;
-- prove isolation: change dev, prod untouched
UPDATE RETAIL_DW_DEV.STAGING.DIM_CUSTOMER SET CITY='DEVTEST' WHERE CUSTOMER_ID='C000002';
SELECT 'prod' src, CITY FROM RETAIL_DW.STAGING.DIM_CUSTOMER     WHERE CUSTOMER_ID='C000002'
UNION ALL
SELECT 'dev', CITY FROM RETAIL_DW_DEV.STAGING.DIM_CUSTOMER WHERE CUSTOMER_ID='C000002';
