-- Snowflake trial execution path: no AWS account required.
-- This seeds realistic synthetic data in RAW, then exercises Streams, Tasks,
-- SCD Type 2, RBAC/masking, and warehouse optimization.  Use scripts 01-05
-- with an AWS S3 account when you are ready to demonstrate live Snowpipe.

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS LOAD_WH
  WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=TRUE;
CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH
  WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=TRUE;
CREATE WAREHOUSE IF NOT EXISTS BI_WH
  WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=TRUE;

CREATE DATABASE IF NOT EXISTS RETAIL_DW;
CREATE SCHEMA IF NOT EXISTS RETAIL_DW.RAW;
CREATE SCHEMA IF NOT EXISTS RETAIL_DW.STAGING;
CREATE SCHEMA IF NOT EXISTS RETAIL_DW.ANALYTICS;
USE DATABASE RETAIL_DW;
USE WAREHOUSE TRANSFORM_WH;

CREATE OR REPLACE TABLE RAW.ORDERS_RAW (
  ORDER_ID STRING, CUSTOMER_ID STRING, ORDER_TS STRING, STATUS STRING,
  CHANNEL STRING, ITEMS STRING, ORDER_TOTAL STRING,
  _SOURCE_FILE STRING, _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());
CREATE OR REPLACE TABLE RAW.CUSTOMERS_RAW (
  CUSTOMER_ID STRING, FULL_NAME STRING, EMAIL STRING, PHONE STRING, CITY STRING,
  STATE STRING, SIGNUP_DATE STRING, UPDATED_AT STRING,
  _SOURCE_FILE STRING, _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());

CREATE OR REPLACE TABLE STAGING.DIM_CUSTOMER (
  CUSTOMER_SK NUMBER IDENTITY START 1 INCREMENT 1, CUSTOMER_ID STRING NOT NULL,
  FULL_NAME STRING, EMAIL STRING, PHONE STRING, CITY STRING, STATE STRING,
  SIGNUP_DATE DATE, VALID_FROM TIMESTAMP_NTZ NOT NULL, VALID_TO TIMESTAMP_NTZ,
  IS_CURRENT BOOLEAN NOT NULL DEFAULT TRUE);
CREATE OR REPLACE TABLE ANALYTICS.FACT_ORDERS (
  ORDER_ID STRING NOT NULL, CUSTOMER_SK NUMBER, ORDER_TS TIMESTAMP_NTZ,
  ORDER_DATE DATE, STATUS STRING, CHANNEL STRING, ITEMS NUMBER,
  ORDER_TOTAL NUMBER(12,2), _UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());

CREATE OR REPLACE STREAM RAW.CUSTOMERS_STREAM ON TABLE RAW.CUSTOMERS_RAW;
CREATE OR REPLACE STREAM RAW.ORDERS_STREAM ON TABLE RAW.ORDERS_RAW;

-- 5,000 customers and 50,000 orders: enough volume to demonstrate incremental ELT
INSERT INTO RAW.CUSTOMERS_RAW
SELECT 'C'||LPAD((SEQ4()+1)::STRING,6,'0'),
       'Customer '||(SEQ4()+1), 'customer'||(SEQ4()+1)||'@example.com',
       '703-555-'||LPAD(MOD(SEQ4(),10000)::STRING,4,'0'),
       IFF(MOD(SEQ4(),2)=0,'Fairfax','Arlington'), 'VA', '2025-01-01',
       '2026-05-01 00:00:00', 'trial_seed_customers.csv'
FROM TABLE(GENERATOR(ROWCOUNT => 5000));
INSERT INTO RAW.ORDERS_RAW
SELECT 'O'||LPAD((SEQ4()+1)::STRING,8,'0'),
       'C'||LPAD((MOD(SEQ4(),5000)+1)::STRING,6,'0'),
       TO_VARCHAR(DATEADD('minute',SEQ4(),'2026-03-01 00:00:00'::TIMESTAMP_NTZ)),
       IFF(MOD(SEQ4(),10)=0,'returned','delivered'),
       CASE MOD(SEQ4(),3) WHEN 0 THEN 'web' WHEN 1 THEN 'mobile' ELSE 'store' END,
       (MOD(SEQ4(),8)+1)::STRING, (20+MOD(SEQ4(),380))::STRING,
       'trial_seed_orders.csv'
FROM TABLE(GENERATOR(ROWCOUNT => 50000));

CREATE OR REPLACE PROCEDURE STAGING.SP_MERGE_DIM_CUSTOMER()
RETURNS STRING LANGUAGE SQL AS
$$
BEGIN
  CREATE OR REPLACE TEMPORARY TABLE STAGING._CUST_DELTA AS
  SELECT CUSTOMER_ID,FULL_NAME,EMAIL,PHONE,CITY,STATE,TRY_TO_DATE(SIGNUP_DATE) SIGNUP_DATE,
         TRY_TO_TIMESTAMP(UPDATED_AT) UPDATED_AT
  FROM RAW.CUSTOMERS_STREAM WHERE METADATA$ACTION='INSERT'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY TRY_TO_TIMESTAMP(UPDATED_AT) DESC)=1;
  MERGE INTO STAGING.DIM_CUSTOMER d USING STAGING._CUST_DELTA s
    ON d.CUSTOMER_ID=s.CUSTOMER_ID AND d.IS_CURRENT
  WHEN MATCHED AND (NOT EQUAL_NULL(d.CITY,s.CITY) OR NOT EQUAL_NULL(d.EMAIL,s.EMAIL)
                    OR NOT EQUAL_NULL(d.PHONE,s.PHONE) OR NOT EQUAL_NULL(d.FULL_NAME,s.FULL_NAME))
    THEN UPDATE SET VALID_TO=s.UPDATED_AT, IS_CURRENT=FALSE;
  INSERT INTO STAGING.DIM_CUSTOMER
    (CUSTOMER_ID,FULL_NAME,EMAIL,PHONE,CITY,STATE,SIGNUP_DATE,VALID_FROM,VALID_TO,IS_CURRENT)
  SELECT s.CUSTOMER_ID,s.FULL_NAME,s.EMAIL,s.PHONE,s.CITY,s.STATE,s.SIGNUP_DATE,
         COALESCE(s.UPDATED_AT,CURRENT_TIMESTAMP()),NULL,TRUE
  FROM STAGING._CUST_DELTA s LEFT JOIN STAGING.DIM_CUSTOMER d
    ON d.CUSTOMER_ID=s.CUSTOMER_ID AND d.IS_CURRENT
  WHERE d.CUSTOMER_ID IS NULL;
  RETURN 'DIM_CUSTOMER merged';
END;
$$;

CREATE OR REPLACE PROCEDURE ANALYTICS.SP_MERGE_FACT_ORDERS()
RETURNS STRING LANGUAGE SQL AS
$$
BEGIN
  MERGE INTO ANALYTICS.FACT_ORDERS f USING (
    SELECT o.ORDER_ID,d.CUSTOMER_SK,TRY_TO_TIMESTAMP(o.ORDER_TS) ORDER_TS,
           TO_DATE(TRY_TO_TIMESTAMP(o.ORDER_TS)) ORDER_DATE,o.STATUS,o.CHANNEL,
           TRY_TO_NUMBER(o.ITEMS) ITEMS,TRY_TO_DECIMAL(o.ORDER_TOTAL,12,2) ORDER_TOTAL
    FROM RAW.ORDERS_STREAM o LEFT JOIN STAGING.DIM_CUSTOMER d
      ON d.CUSTOMER_ID=o.CUSTOMER_ID AND d.IS_CURRENT
    WHERE o.METADATA$ACTION='INSERT'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY o.ORDER_ID ORDER BY TRY_TO_TIMESTAMP(o.ORDER_TS) DESC)=1
  ) s ON f.ORDER_ID=s.ORDER_ID
  WHEN MATCHED THEN UPDATE SET STATUS=s.STATUS,ORDER_TOTAL=s.ORDER_TOTAL,_UPDATED_AT=CURRENT_TIMESTAMP()
  WHEN NOT MATCHED THEN INSERT (ORDER_ID,CUSTOMER_SK,ORDER_TS,ORDER_DATE,STATUS,CHANNEL,ITEMS,ORDER_TOTAL)
    VALUES (s.ORDER_ID,s.CUSTOMER_SK,s.ORDER_TS,s.ORDER_DATE,s.STATUS,s.CHANNEL,s.ITEMS,s.ORDER_TOTAL);
  RETURN 'FACT_ORDERS merged';
END;
$$;

CALL STAGING.SP_MERGE_DIM_CUSTOMER();
CALL ANALYTICS.SP_MERGE_FACT_ORDERS();

-- Increment: version one customer and add 100 orders.
INSERT INTO RAW.CUSTOMERS_RAW VALUES
('C000001','Customer 1','customer1@example.com','703-555-0000','Denver','CO','2025-01-01','2026-05-02 00:00:00','trial_increment_customers.csv',CURRENT_TIMESTAMP());
INSERT INTO RAW.ORDERS_RAW
SELECT 'O'||LPAD((50001+SEQ4())::STRING,8,'0'),'C000001',
       TO_VARCHAR(DATEADD('minute',SEQ4(),'2026-05-02 00:00:00'::TIMESTAMP_NTZ)),
       'delivered','web','2','49.99','trial_increment_orders.csv',CURRENT_TIMESTAMP()
FROM TABLE(GENERATOR(ROWCOUNT => 100));
CALL STAGING.SP_MERGE_DIM_CUSTOMER();
CALL ANALYTICS.SP_MERGE_FACT_ORDERS();

CREATE OR REPLACE TASK ANALYTICS.TASK_LOAD_DIMS
  WAREHOUSE=TRANSFORM_WH SCHEDULE='USING CRON */5 * * * * UTC'
  WHEN SYSTEM$STREAM_HAS_DATA('RETAIL_DW.RAW.CUSTOMERS_STREAM')
    OR SYSTEM$STREAM_HAS_DATA('RETAIL_DW.RAW.ORDERS_STREAM')
AS CALL STAGING.SP_MERGE_DIM_CUSTOMER();
CREATE OR REPLACE TASK ANALYTICS.TASK_LOAD_FACTS
  WAREHOUSE=TRANSFORM_WH AFTER ANALYTICS.TASK_LOAD_DIMS
AS CALL ANALYTICS.SP_MERGE_FACT_ORDERS();
ALTER TASK ANALYTICS.TASK_LOAD_FACTS RESUME;
ALTER TASK ANALYTICS.TASK_LOAD_DIMS RESUME;

CREATE ROLE IF NOT EXISTS DE_ENGINEER;
CREATE ROLE IF NOT EXISTS DE_ANALYST;
CREATE ROLE IF NOT EXISTS DE_VIEWER;
GRANT ROLE DE_VIEWER TO ROLE DE_ANALYST;
GRANT ROLE DE_ANALYST TO ROLE DE_ENGINEER;
GRANT USAGE ON DATABASE RETAIL_DW TO ROLE DE_VIEWER;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE DE_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS TO ROLE DE_VIEWER;
GRANT USAGE ON SCHEMA STAGING TO ROLE DE_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA STAGING TO ROLE DE_ANALYST;
CREATE OR REPLACE MASKING POLICY STAGING.MASK_EMAIL AS (VAL STRING) RETURNS STRING ->
  IFF(CURRENT_ROLE() IN ('ACCOUNTADMIN','DE_ENGINEER'),VAL,CONCAT(LEFT(VAL,2),'****@masked.com'));
ALTER TABLE STAGING.DIM_CUSTOMER MODIFY COLUMN EMAIL SET MASKING POLICY STAGING.MASK_EMAIL;
ALTER TABLE ANALYTICS.FACT_ORDERS CLUSTER BY (ORDER_DATE);

SELECT COUNT(*) AS DIM_CURRENT FROM STAGING.DIM_CUSTOMER WHERE IS_CURRENT;
SELECT COUNT(*) AS FACT_ORDERS FROM ANALYTICS.FACT_ORDERS;
SELECT CUSTOMER_ID,CITY,VALID_FROM,VALID_TO,IS_CURRENT FROM STAGING.DIM_CUSTOMER
WHERE CUSTOMER_ID='C000001' ORDER BY VALID_FROM;
SELECT ORDER_DATE,CHANNEL,COUNT(*) ORDERS,SUM(ORDER_TOTAL) REVENUE
FROM ANALYTICS.FACT_ORDERS GROUP BY 1,2 ORDER BY 1,2 LIMIT 20;
